name: C/C++ CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build
      run: make -j
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: mandelbrot
